### ISSUE TITLE
Inappropriate role attributes in dropdowns

### ISSUE THREAD

**Issue by tmcgill** [paypal/bootstrap-accessibility-plugin#101]
dropdown.js, lines 9 and 12:

The addition of role="menu" to the `<ul>` element and role="menuitem" to the  `<a>` element makes sense when Bootstrap dropdowns are used within a web app and the dropdown items provide functions within the app. However, when dropdowns are used in navigational structures  role="menu" and role="menuitem" aren't appropriate. Also, adding role="presentation" to each `<li>` element isn't necessary because the native `<li>` role already has the correct semantics.

I recommend removing these attribute injections so that web developers using the accessibility plugin can select the correct roles for their usage needs.

**Comment by mpnkhan** [comment]
We think in most of the cases which we noticed, the developers simply try to copy paste the bootstrap code and hence, missing the Aria roles. The number of ARIA unaware developers are far more than the people who use it  in navigational structure. 
But the correct way to fix would be to use different classes when used in navigation and when used it as dropdown, so the plugin code could create an exception of roles.
