### ISSUE TITLE
Modal isn't going back to where it was -BS 3.3.7, 1.0.5 accessibility

### ISSUE THREAD

**Issue by veenarm** [paypal/bootstrap-accessibility-plugin#118]
Hi,

I just started using it to solve our modal accessibility issues and it was going awesome, e.g. locking modals tabbing into itself, never letting it outside the frame, but when we close our modals they then set it back to the 'browser' (one before the URL) and start from scratch..

Any idea how to fix this? I tried downgrading versions of both this plugin and boostrap css to 3.3.0 and 3.1.1 which had no impact, actually going backwards in bootstrap broke the tab locking.

Regards
John

**Comment by mpnkhan** [comment]
Try this 
$('#myModal').on('hidden.bs.modal', function () {
//set focus where you want to 
})

**Comment by veenarm** [comment]
Ty, I'll give it a go when back at work - should fix 98% of our cases, sometimes we have 2 different places opening the same modal, either more js to id which one opened it which is fine, or just duplicate the modals with different ids, easy enough as using component based JSF. tyvm for this plugin though saved me so much time trying to make it WCAG AA myself :)

**Comment by veenarm** [comment]
Cheers - That seems to resolve my issues although I have to manually do it though, any ideas on what could cause the accessibility.js to not trigger the correct focus event?

**Comment by mpnkhan** [comment]
TY! That depends on how the content is dynamically called and if the bs-a11y plugin is called after modal content is rendered etc. Try setting breakpoint in the plugin code and check if and all that is called
