### ISSUE TITLE
Modal not able to tab to new elements due to enforcefocus function

### ISSUE THREAD

**Issue by chenchenalex** [paypal/bootstrap-accessibility-plugin#119]
https://github.com/paypal/bootstrap-accessibility-plugin/blob/5d1b9bd823c54e9c2e40c80bf47c3149db646d01/src/js/modal.js#L20

Hello, There seems to be an issue when new elements is displayed in the modal but cannot be tabbed, this is caused by the last element has a keydown event which trap the tabbing and direct focus to the first element.

 Is there any way to refresh the modal to fix this? Thanks

**Comment by mpnkhan** [comment]
When new element is displayed, try calling $(document).off('keydown.bs.modal') and enForce focus again.

**Comment by chenchenalex** [comment]
Thanks  for answering.

Sorry, what version of BS can cover all these accessibilities? This library was introduced by another developer, I was just fixing a bug and found this

**Comment by mpnkhan** [comment]
BS4
