### ISSUE TITLE
1.0.5 release?

### ISSUE THREAD

**Issue by demiankatz** [paypal/bootstrap-accessibility-plugin#120]
I realize that this project is winding down due to the release of Bootstrap 4... but for those of us still using it, would it be possible to mint a 1.0.5 release? 1.0.4 came out in 2014, and there seems to have been significant development in master since then; it would be nice to be able to take advantage of this through Bower, for example.

**Comment by mpnkhan** [comment]
+ bootstrap-accessibility-plugin@1.0.6

**Comment by demiankatz** [comment]
@mpnkhan, I see 1.0.6 on NPM (https://libraries.io/npm/bootstrap-accessibility-plugin/1.0.6), but it does not appear to be tagged in this repository, and I cannot load it through Bower. Am I missing something?

**Comment by mpnkhan** [comment]
I was not sure why it didn't list. $ git show v1.0.6 listed the changes and npm install also worked. 
Now have updated bower.json and manually tagged to 1.0.7. 
This should work:
bower install bootstrapaccessibilityplugin#1.0.7

**Comment by demiankatz** [comment]
Thanks, @mpnkhan, it is working now. I appreciate the help!
