### ISSUE TITLE
Backward compatible with older BS 2.3.2?

### ISSUE THREAD

**Issue by emage** [paypal/bootstrap-accessibility-plugin#58]
Our company has been designed using the older version of BS.  Upgrading to 3+ would required alot of changing both front and back.

**Comment by Hani79** [comment]
@mpnkhan - does your response to @emage mean that there exists a version of this plugin that works properly with Bootstrap 2.3.2? If so, is it still available?

**Comment by mpnkhan** [comment]
yes Its still available. should be there in 3.1 folder https://github.com/paypal/bootstrap-accessibility-plugin/tree/master/bs3.1.1

**Comment by Hani79** [comment]
Thanks, @mpnkhan! I was able to find it.
