### ISSUE TITLE
Input Field in Dropdown cannot be focused by click

### ISSUE THREAD

**Issue by janwalther** [paypal/bootstrap-accessibility-plugin#6]
I have an input field inside a button dropdown menu. With plain BS3 I can focus it by clicking with the mouse. With BS Accessibility the dropdown menu closes once I click the input field. The problem is this part (from line 117 in bootstrap-accessibility.js):

```
.on('focusout.dropdown.data-api', '.dropdown-menu', function(e){
        var $this = $(this)
        setTimeout(function() {
         if(!$(document.activeElement).is($this.find("a"))){
          $this.parent().removeClass('open')
          $this.parent().find('[data-toggle=dropdown]').attr('aria-expanded','false')
         }
        }, 150)
       })
```

Only if the clicked element is a link ("a" tag), the dropdown stays open.

**Comment by yokiking** [comment]
Is that enough? could we make it work with mouse?
And once we wanna copy edit with mouse in that field, the drop down will disappear too.
