### ISSUE TITLE
Question: Correct way to load bootstrap-accessibility

### ISSUE THREAD

**Issue by mdgbayly** [paypal/bootstrap-accessibility-plugin#66]
I'm probably missing something really dumb here, but I don't understand the correct way to load this plugin.

The default instructions say just add to your scripts section after bootstrap.
However the plugin contains lots of DOM manipulation code like:

$('.alert').attr('role', 'alert')

This runs before our dom is ready so none of these DOM manipulations get applied.

What am I not understanding?

Thanks
Martin

**Comment by OwenEdwards** [comment]
Just to clarify, although Lazy-loading is an _option_, if this plugin is not Lazy-loaded, it **must** be inserted at the end of the `<body>` of the document, not in the `<head>`; the features do not work if the script is included in the `<head>`. [The section in the README.md](https://github.com/paypal/bootstrap-accessibility-plugin#how-do-i-get-it-on-my-website) **does not** make this clear.

I'm surprised that all the initialization in this plugin isn't wrapped in a `$(function(){...})`, so it gets run on document ready; am I missing something?
