### ISSUE TITLE
Lost tab stop when keyboard cycling thru modal dialog

### ISSUE THREAD

**Issue by becka11y** [paypal/bootstrap-accessibility-plugin#69]
Using the demo page, open the modal dialog example. Note that when you tab and reach the save changes button, pressing tab one more time does not show anything visibly focused.  Pressing tab again with cycle to the close X button at the top of the dialog.  The extra tab stop is problematic and should be removed.  In my use of the modal in Readium, the extra tab stop goes to the URL bar (tested in Safari).

The same problem happens when shift-tabbing through the modal dialog.  With focus on the close x, pressing shift-tab causes focus to be lost.  Pressing shift-tab again will reach the Save Changes button in the modal dialog.

**Comment by skatejunk** [comment]
+1 on this issue.

This appears to be a bug. Focus is being placed back on the modal container and the anchor/button that triggered the modal. Investigating from my end and will report back with any updates, but for now here's a little script to help diagnose if others want to take a look as well

Running this from console: 
```javascript
$('*').on('focus', function() {
  console.log($(this));
});
```

**Comment by mpnkhan** [comment]
This was some hack done to support shift+tab behaviour.  http://getbootstrap.com/javascript/#modals doesn't support shift+tabbing inside modal container.

**Comment by becka11y** [comment]
Will this ever be fixed correctly?  It really isn't usable to a screen reader user and is confusing to a keyboard user because focus gets lost (even if it is temporary).

**Comment by mpnkhan** [comment]
Please ignore https://github.com/paypal/bootstrap-accessibility-plugin/issues/69#issuecomment-171209860.
Even if i remove modal plugin code, the problem exists.  This problem is inherited from http://getbootstrap.com/javascript/#modals . 

<img width="1275" alt="screen shot 2016-07-13 at 3 40 53 pm" src="https://cloud.githubusercontent.com/assets/2254656/16799875/5d9a2fec-4910-11e6-8b50-6d186a911b55.png">
