### ISSUE TITLE
Sync package names in Bower

### ISSUE THREAD

**Issue by ndarilek** [paypal/bootstrap-accessibility-plugin#71]
At the moment you have to `bower install bootstrapaccessibilityplugin` to install bootstrap-accessibility-plugin (I.e. the value of the name attribute in bower.json.) Noted in mquandalle/meteor-bower#66.

How should this be fixed? Should the package designation be changed to bootstrap-accessibility-plugin in the Bower registry? bootstrapaccessibilityplugin in the name: attribute? I can submit a PR if the latter.

Thanks.

**Comment by mpnkhan** [comment]
Could you kindly submit a PR? 
Thanks in advance.
