### ISSUE TITLE
Screen Reader Compatibility

### ISSUE THREAD

**Issue by bondydaa** [paypal/bootstrap-accessibility-plugin#73]
Greetings,
I could not find a list of screen readers that were used for testing with the plugin. Could you provide a list of what the support is like or what screen readers were tested with this plugin?

Thanks,

**Comment by mpnkhan** [comment]
Its voiceover on Mac with Safari Browser, NVDA on Windows with Firefox and sometimes with  chromevox on  Google chrome for both Mac and Windows.

**Comment by bondydaa** [comment]
Great! Thanks for the info.
