### ISSUE TITLE
Just some thoughts on how to enhance this plugin

### ISSUE THREAD

**Issue by jmuheim** [paypal/bootstrap-accessibility-plugin#74]
Hello. I'm working for [Zugang für alle - Access for all](http://www.access-for-all.ch), an accessibility experts foundation in Switzerland. We do reviews on simple and complex websites on a regular basis, and we have blind expert users here too, so I think we know what we are talking about.

I'm in the process of creating an accessible web app for internal use, and I'd like to use Bootstrap. I was very happy to find this plugin, but I think there are some things that should be optimised. All in all, I'm not very sure whether this plugin is really better then the original Bootstrap, as in some respects, the original seems better, and in other respects it sometimes is hard to say what exactly the plugin adds to the original.

I hope the following list is useful to you.

By the way, I'm using [NVDA](http://www.nvaccess.org/).

## [Modal](http://paypal.github.io/bootstrap-accessibility-plugin/demo.html#modals)

- When the modal is open, I can't use the up and down arrow keys to read the content. Instead, the content of the model is being scrolled. I can only navigate using the tab key, which is **not** how blind people browse a page.
- The X-button to close the dialog is only announced as "button". You should add a description to it, e.g. by using [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) or by providing a hidden text ([move it out of the viewport](http://webaim.org/techniques/css/invisiblecontent/)). The [original demo](http://getbootstrap.com/javascript/#modals) has this already.

## [Dropdown](http://paypal.github.io/bootstrap-accessibility-plugin/demo.html#dropdowns)

- When I press Enter to open a dropdown menu, NVDA automatically enters forms mode. I guess this is because the dropdown is triggered by a button (`role="button"`). This is nasty, because I have to press Esc twice to close the menu.
- I also find it strange that when I don't press Esc (to stay in forms mode), I can't leave the menu anymore (the focus won't move out of the menu). When I press Esc once, then I can leave the menu (I don't even have to close it).

Both of the issues above don't seem to be the case on the original [Bootstrap Navbar demo](http://getbootstrap.com/components/#navbar). In this case, I'd prefer the original over the "accessified" one. In fact, what exactly are you trying to optimise here?

## [Tabs](http://paypal.github.io/bootstrap-accessibility-plugin/demo.html#tabs)

The demo doesn't seem to be initialised properly. When I first browse through the links, they are only announced as "links" without any information about collapsed/expanded status. When I activate the links, they are announced as expanded though. So I think the initialisation process isn't correctly done at the time being.

## [Carousel](http://paypal.github.io/bootstrap-accessibility-plugin/demo.html#carousel)

This also looks better to me on the [original demo](http://getbootstrap.com/javascript/#carousel). For example, the buttons are labelled with "next" and "previous" in the original, while in your demo, they are just blank.

**Comment by vick08** [comment]
Just for the context. When this plugin was created, BOotstrap did not have most of the accessibility features it has now. At this stage we have not performed any comparison between the two and it may very well be that you no longer need the plugin to create accessible websites with Bootstrap.

HTH.


*** *** ***
Find me on Twitter http://www.twitter.com/vick08
