### ISSUE TITLE
Dropdown does not work properly

### ISSUE THREAD

**Issue by CoralSilver** [paypal/bootstrap-accessibility-plugin#78]
I initially installed the plugin through npm, but found this issue referenced here:  #40.

It looks like you made a fix for this  80fd9db which has not been updated in the node version.

Installing current version from this repo, made the dropdown have some very weird behavior, mainly skipping every other link when using the arrow keys. 

I changed ` $toggle.on('keydown.bs.modal', $.proxy(function (ev) {`
to ` $toggle.on('keydown.bs.dropdown', $.proxy(function (ev) {`

and it works as it should.  Is this a bug?

**Comment by mpnkhan** [comment]
Thanks @CoralSilver . Yes its a mistake and thanks for pointing it out. Have fixed and hence closing this bug.
