### ISSUE TITLE
Question: Change to a standard license?

### ISSUE THREAD

**Issue by anitsirk** [paypal/bootstrap-accessibility-plugin#84]
Hello,

Would you consider changing the software license for this plugin to a standard license, e.g. MIT like Bootstrap has, that is GPL 3+ compatible? That would make it easier for other projects to use the plugin. We maintain an open source codebase and would most likely not be able to use your plugin under its current license.

Thank you
Kristina

**Comment by DuaneOBrien** [comment]
@anitsirk thanks so much for your issue.

The software license is the BSD 3 Clause (Modified BSD) - http://opensource.org/licenses/BSD-3-Clause

This should be compatible with GPL 3+ - https://www.gnu.org/licenses/license-list.html#ModifiedBSD

Is there something in particular WRT to licensing in the repo that's causing an issue for you?

Thanks!
-Duane

**Comment by anitsirk** [comment]
Hello Duane,

Thank you very much for the clarification around the license. We'll review if the plugin adds functionality that we require or whether Bootstrap's in-built functionality is sufficient now that more accessibility features have been included. Knowing that your license is the Modified BSD one will make it possible to use the plugin if needed at some point.

Thank you
Kristina

**Comment by DuaneOBrien** [comment]
@anitsirk happy to help, please don't hesitate to reach out if you have additional questions or concerns.
