### ISSUE TITLE
Labels written in english : not multilingual

### ISSUE THREAD

**Issue by yjajkiew** [paypal/bootstrap-accessibility-plugin#96]
Hi,

I'm just writing this issue to ask if it wouldn't be cleaner to have the texts written in english translatable ? There's only two strings used by the carousel (like 'Show slide x of y') but by putting them in a array by exemple it would be easier to manage multilingual settings.

Best regards,
Yann

**Comment by mpnkhan** [comment]
Different packages do  I18 and  L10 differently.   In a react world, the strings would usually  come from local properties. It is based on the whole project, instead of this single package
